### ISSUE TITLE
Not working on iOS with mov files

### ISSUE THREAD

**Issue by Bayramito** [numandev1/react-native-compressor#101]
### Current behavior

Its not working on IOS with .mov file format at all.

### Platform

- [X] iOS

### React Native Version

react-native: "0.64.2"

### React Native Compressor Version
react-native-compressor: "0.5.17"

**Comment by pierroo** [comment]
@Bayramito did you find any solution to this? 
it is quite sad indeed :/

**Comment by stefanleoussis** [comment]
@Bayramito Yes indeed

**Comment by Bayramito** [comment]
> @Bayramito Yes indeed
I used a converter in a promisr and used mp4.

but it might work on the newest version i think.

**Comment by talha-mts** [comment]
Any update it's still not working.
& also application crashes whenever we try to compress mov file.

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by vincentzierigen** [comment]
We need an urgent fix for this, the app crashes every single time

**Comment by numandev1** [comment]
@vincentzierigen it is working on my side with mov file, can you send me your mov file so i can reproduce this issue on my side and fix it

**Comment by numandev1** [comment]
@vincentzierigen did you check latest version?

**Comment by vincentzierigen** [comment]
> @vincentzierigen did you check latest version?

I just did and now it works! Thank you so much!
