### ISSUE TITLE
Size bigger on iOS AFTER compressing

### ISSUE THREAD

**Issue by pierroo** [numandev1/react-native-compressor#109]
### Current behavior
Instead of reducing final file size, on iOS it seems that the image compressor 'auto' increase the image size.
Which is exactly what we don't want.
Installation went well, so I'm really confused. Works well on android (for images at least)
Images go from 200kb to 350kb (taken from gallery / imagePicker)
### Platform

- [X] iOS

### React Native Version
0.66.0
### React Native Compressor Version
1.5.2

**Comment by ya-ushel** [comment]
Have same issue

**Comment by numandev1** [comment]
@pierroo 🙏 🙏 sorry a long ago I was not maintaining  due to the office workload, hopefully, I am going to start fixing bugs on a weekend basis

**Comment by numandev1** [comment]
@andresmejia3 can you attach an image that is getting a higher size after compression? I don't have any image that is getting a higher size

**Comment by numandev1** [comment]
@andresmejia3 ?

**Comment by numandev1** [comment]
fixed and released in `1.8.12`, can you try
