### ISSUE TITLE
On IOS is work fine, but Android always error null

### ISSUE THREAD

**Issue by Fudci** [numandev1/react-native-compressor#115]
LOG  {"error": [Error: null]} compression error

This is my code :

const dstUrl = await Video.compress(
        sourceVideo,
        {
          compressionMethod: 'auto',
          // minimumFileSizeForCompress: 5,
          // maxSize: 1000,
          minimumFileSizeForCompress:1
        },
        (progress) => {
          if (backgroundMode) {
            console.log('Compression Progress: ', progress);
          } else {
            setCompressingProgress(progress);
          }
        }
      );

**Comment by Liqiankun** [comment]
@Fudci same issue.

**Comment by Liqiankun** [comment]
@nomi9995

**Comment by mani627** [comment]
I have Also same issue ..

**Comment by mani627** [comment]
Please reply ASAP....

................................................................................................................
 try {
            let result = await Video.compress(
             response.assets["0"].uri  ,
              { compressionMethod: 'auto',


            },
              (progress) => {
                if (backgroundMode) {
                  console.log('Compression Progress: ', progress);
                } else {
                  setCompressingProgress(progress);
                }
              }
            )
            console.log('compression result', result);
          } catch (error) {
            console.log(error , 'compression error');

          }
................................................................................

i used realpath uri and temporary path uri (content://),   but both gives same error like   ->LOG {"error": [Error: null]} compression error

**Comment by fs-ahsan** [comment]
Same issue any solution @mani627 @Liqiankun

**Comment by hsilvap** [comment]
same issue

**Comment by harleenarora** [comment]
any solution?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in latest version
