### ISSUE TITLE
While upload video the request data is empty on server.

### ISSUE THREAD

**Issue by remorr25** [numandev1/react-native-compressor#118]
### Current behavior
Video compressing fine but when I try to upload on server, request  data is empty but in response I am getting {status:200}

### Expected behavior
File should be upload on server.

### Platform

- [] Android

### React Native Version
0.69.1

### React Native Compressor Version
1.5.2

### Reproducible Steps And Demo
Setup up the environment with react-native 0.69.1 and build the example which can be find inside the  git repo of plugin.

**Comment by hmShuvo314** [comment]
Hi any update on this? I am also having similar issue.
