### ISSUE TITLE
 error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by Bayramito** [numandev1/react-native-compressor#123]
### Current behavior
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-compressor:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/bm3/Desktop/srs/mzapp/node_modules/react-native-compressor/android/build/intermediates/merged_res/release/values/values.xml:2723: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
### Platform

- [X] Android

### React Native Version
0.70.1

### React Native Compressor Version
1.5.2

**Comment by evaldovega** [comment]
Replace gradlew assembleRelease to  gradlew app:assembleRelease

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed by @evaldovega comment https://github.com/numandev1/react-native-compressor/issues/123#issuecomment-1562135367
