### ISSUE TITLE
destination path is error

### ISSUE THREAD

**Issue by Milker90** [numandev1/react-native-compressor#136]
### Current behavior
destinationPath is "file:/"+destinationPath，sometime android will cause "No such file or directory"

eg:
```
await fetch(destinationPath)
```
will throw "TypeError: Network request failed"

### Expected behavior
destinationPath is "file://"+destinationPath

### Platform

- [X] Android
- [ ] iOS

### React Native Version
"react-native": "0.70.6"

### React Native Compressor Version
"react-native-compressor": "1.6.1"

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
