### ISSUE TITLE
[Android] Returned path should start with `file:///data...` instead of `file://...`

### ISSUE THREAD

**Issue by hrastnik** [numandev1/react-native-compressor#137]
### Current behavior
Returned path starts with `file://data` making the URI invalid

### Expected behavior
Return path should start with `file:///data...`. 

This fixes the issue:
```
const uri = brokenURI.startsWith("file://") && !brokenURI.startsWith("file:///") ? brokenURI.replace("file://", "file:///") : brokenURI;
```

or shorter
```
const uri = brokenURI.replace(/^file:\/\/([^/])/, "file:///$1");
```

### Platform

- [X] Android

### React Native Version
0.70.6

### React Native Compressor Version
1.6.1

**Comment by iasreact1** [comment]
@hrastnik   please help me to solve the issue
FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':react-native-compressor:compileDebugAidl'.
Could not resolve all task dependencies for configuration ':react-native-compressor:debugCompileClasspath'.
Could not resolve io.github.lizhangqu:coreprogress:1.0.2.
Required by:
project :react-native-compressor
> Skipped due to earlier error
> Skipped due to earlier error

after installing react-native-compressor-1.6.1 and with react-native-0.70.6 ....Please help sir

**Comment by falmesino** [comment]
I just want to say thank you, i didn't notice the missing "/".

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@hrastnik @falmesino can you check this issue by latest version of this package?

**Comment by hrastnik** [comment]
Just tested it, looks good!
