### ISSUE TITLE
Background compression not working in android

### ISSUE THREAD

**Issue by hkhan6916** [numandev1/react-native-compressor#139]
### Current behavior
Background compression stops for videos larger than 35mb on slightly older devices such as a Galaxy s10. Works fine on newer higher end devices.
### Expected behavior
Background compression should complete for videos larger than 35mb using a device like a Galaxy s10.
### Platform

- [X] Android
- [] iOS

### React Native Version
0.70.5

### React Native Compressor Version
1.5.2

### Reproducible Steps And Demo
Supply a 50MB video to react native compressor using an older device and then immediately background the app. The compression stops after around 1-2 mins.

**Comment by iasreact1** [comment]
@hkhan6916 please help me to solve the issue 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-compressor:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-compressor:debugCompileClasspath'.
   > Could not resolve io.github.lizhangqu:coreprogress:1.0.2.
     Required by:
         project :react-native-compressor
      > Skipped due to earlier error
      > Skipped due to earlier error

 after installing react-native-compressor-1.6.1 and with react-native-0.70.6  ....Please help sir

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen this issue again if this issue happens again
