### ISSUE TITLE
On installation showing error Could not resolve io.github.lizhangqu:coreprogress:1.0.2.

### ISSUE THREAD

**Issue by iasreact1** [numandev1/react-native-compressor#140]
My react-native - 0.70.6 
and used react-native-compressor - 1.6.1
 after installing using command  npm i react-native-compressor  when i run the project  it will threw an error 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-compressor:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-compressor:debugCompileClasspath'.
   > Could not resolve io.github.lizhangqu:coreprogress:1.0.2.
     Required by:
         project :react-native-compressor
      > Skipped due to earlier error
      > Skipped due to earlier error
Please help to fix the issue ...

**Comment by iasreact1** [comment]
@mlecoq  @alariej  @numandev1  @closetothe  Please help to overcome the issue

**Comment by mlecoq** [comment]
@iasreact1  I don’t reproduce this issue, do you have an example to reproduce it

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@iasreact1 is this issue reproducing again?

**Comment by numandev1** [comment]
removed `io.github.lizhangqu:coreprogress` implementation completely
