### ISSUE TITLE
Codec is changed while compress from the android. 

### ISSUE THREAD

**Issue by KishanGondaliya1** [numandev1/react-native-compressor#141]
### Current behavior
Codec  -->  H.264
### Expected behavior
Codec -->  AAC, H.264
### Platform
- [X] Android

### React Native Version
0.68.2
### React Native Compressor Version
^1.6.1

### Reproducible Steps And Demo
Compress video from the android and then upload on the server. But that video is not playing on the web
due to the change in "Codec"  AAC is not there[removed] after the video compression.

**Comment by KishanGondaliya1** [comment]
@numandev1 Can you please help with this issue? If any video has the Codec - AAC and then compress that video from android then it is removing the codec - AAC and after that this video is not working on the web video player. However, it is working on all other scenarios. 

Thanks

**Comment by KishanGondaliya1** [comment]
@mlecoq @alariej @numandev1 @closetothe Can you please help with this issue?

**Comment by petrmacal** [comment]
Same issue here. Original file has AAC, H.264, the result H.264 only. Video cannot be played in HTML5 video player, but playable in VLC (although, obviously, without sound). HTML5 embedded video player shows black screen. Any ideas how to solve the issue, please?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed by https://github.com/numandev1/react-native-compressor/pull/180

**Comment by numandev1** [comment]
fixed in `1.8.2`

**Comment by KishanGondaliya1** [comment]
Thank you very much @numandev1

**Comment by numandev1** [comment]
🙏 please try `1.8.3` as `1.8.2` has one error
