### ISSUE TITLE
Video not playing in ExoPlayer after compression

### ISSUE THREAD

**Issue by DaneHoward** [numandev1/react-native-compressor#143]
### Current behavior
After the video is compressed, the video will no longer play in Android ExoPlayer with given error: 

 Error occured:  {"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}

** I saw some closed tickets and tried variations of file:// and file:/// but neither was playable.

### Expected behavior
Video plays in Android video player

### Platform

- [X] Android

### React Native Version
RN: 0.70.6

### React Native Compressor Version
RNC: ^1.6.1

### Reproducible Steps And Demo
1. install React Native Compressor
2. Enable android exoplayer as media player
This is done by changing react-native.config.js to
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir:
            '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },

3. Compress the video as directed and send the URL to a React Native Video component

**Comment by DaneHoward** [comment]
> 👋 @DaneHoward
>  Thanks for opening your issue here! **If you find this package useful hit the star🌟!**

It is useful so I went ahead and gave it a star. Everything else besides compress on Android works like a dream!

**Comment by maurobender** [comment]
I'm experiencing the same issue in one of my projects, have you found any solution to this @DaneHoward ?

**Comment by topwebtek7** [comment]
Any workaround for this issue yet? I'm experiencing same issue now

**Comment by DaneHoward** [comment]
@maurobender @topwebtek7 I was able to make it work by doing an await on the auto compression setting in an async function and outputting the progress along the way. Verify that your video component is looking at the correct URI and verify that the video exists at that location by using the metadata tags provided in this package.

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
fixed in the latest version, please feel free to reopen if you get any error
