### ISSUE TITLE
[iOS] Cannot find Compressor-Bridging-Header

### ISSUE THREAD

**Issue by DanC5** [numandev1/react-native-compressor#144]
@numandev1 I am receiving a similar Bridging Header error referenced in other issues while trying to do the bare React Native setup. My environment...

- React Native v0.66.4,
- react-native-compressor - v1.6.1
- iOS 16.2

The error...

`Build input file cannot be found: '/<my_app_info>/node_modules/react-native-compressor/ios/Video/Compressor-Bridging-Header.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

Upon inspecting node_modules, it looks like the Bridging Header it's looking for is locating one directory up, outside of Video.

![Screen Shot 2023-01-23 at 7 06 26 AM](https://user-images.githubusercontent.com/43552931/214059489-c5ac7674-13c2-4d65-bce7-915b239c4107.png)

I believe I've handled the setup properly, but let me know if you have thoughts on what could be going wrong.

![Screen Shot 2023-01-23 at 7 18 29 AM](https://user-images.githubusercontent.com/43552931/214062260-01b2eb08-dcf6-434b-84e0-4fcc770be63c.png)

![Screen Shot 2023-01-23 at 7 20 35 AM](https://user-images.githubusercontent.com/43552931/214062746-8d2ca4a2-5d8b-41d8-ab35-80e368bcb4df.png)

**Comment by mizzyexists** [comment]
Were you able to make any progress on this @DanC5?

**Comment by DanC5** [comment]
> Were you able to make any progress on this @DanC5? I'm having the same issue and have tried a couple things to no avail.

I was not able to get this problem fixed, so I ended up using https://www.npmjs.com/package/ffmpeg-kit-react-native which works quite nicely. I'm happy to share a code snippet if you need a jumpstart getting that one going.

**Comment by mizzyexists** [comment]
> I was not able to get this problem fixed, so I ended up using https://www.npmjs.com/package/ffmpeg-kit-react-native which works quite nicely. I'm happy to share a code snippet if you need a jumpstart getting that one going.

@DanC5, It's funny because I'm decided to go the exact same route with ffmpegkit. Turns out, the image picker I'm using to upload the video has built in video compression for iOS, so I'm only going to have to use ffmpeg for compressing uploads from android devices. Just out of curiosity, would you mind sharing your ffmpeg params? Not super familiar with it out of the box. Thanks!

**Comment by DanC5** [comment]
> @DanC5, It's funny because I decided to go the exact same route with ffmpegkit. Turns out, the image picker I'm using to upload the video has built in video compression for iOS, so I'm only going to have to use ffmpeg for compressing uploads from android devices. Just out of curiosity, would you mind sharing your ffmpeg params? Not super familiar with it out of the box. Thanks!

No problem. And yeah the syntax is pretty funky, too a minute to get it working as intended. I'm using https://github.com/react-native-image-picker/react-native-image-picker to grab the video file and `uri` in my below example is the picked video file from the device. Essentially you create a temp file using react-native-fs and then direct FFmpegKit to save its output to that path. You then read that temp file and do whatever you want with the resulting compressed video.

```
const outputPath = `${RNFS.CachesDirectoryPath}/${uuidv4()}.mp4`;
await FFmpegKit.execute(`-y -i ${uri} -c:v mpeg4 ${outputPath}`); // add -s:v 720x1280 if you want to lock in scale
const base64Video = await RNFS.readFile(outputPath, 'base64');
```

**Comment by mizzyexists** [comment]
Much appreciated @DanC5! Very clean and simple! 🔥

**Comment by DanC5** [comment]
> Much appreciated @DanC5! Very clean and simple! 🔥

Happy to help!

**Comment by BenSaxon** [comment]
I'm also getting the same issue. Will try https://www.npmjs.com/package/ffmpeg-kit-react-native instead. Thanks for the info!

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
already fixed
