### ISSUE TITLE
Not getting the url of the file

### ISSUE THREAD

**Issue by Karan-Rampal** [numandev1/react-native-compressor#152]
### Current behavior
not getting the url
### Expected behavior
should return the compressed url
### Platform

- [X] Android
- [X] iOS

### React Native Version
0.71.7
### React Native Compressor Version
1.6.1
### Reproducible Steps And Demo
import React, { useState, useEffect } from 'react';
import { SafeAreaView, ScrollView, Text, View } from 'react-native';
import { Image } from 'react-native-compressor';

function App() {
  const [compressedImage, setCompressedImage] = useState('');

  useEffect(() => {
    compressImage();
  });

  async function compressImage() {
    const result = await Image.compress('https://media.istockphoto.com/id/1420039900/photo/cyber-security-ransomware-email-phishing-encrypted-technology-digital-information-protected.jpg?s=2048x2048&w=is&k=20&c=H2DW0WcG6v9JZow-0XW31UVcCV63q41zpJk-d8kmIY0=', {
      maxWidth: 1000,
      quality: 0.8,
    });
    setCompressedImage(result);
  }

  return (
    <SafeAreaView>
      <ScrollView contentInsetAdjustmentBehavior="automatic">
        <View>
          <Text>{compressedImage}</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
export default App;

**Comment by sreehari-kt** [comment]
AFAIK, This library doesn't handle remote network files. You should download and save the image locally before calling ```compress()```

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@sreehari-kt in latest version it supports remote network files, you can test
