### ISSUE TITLE
Video compress does not reduce video size more than 50% from orignal size 

### ISSUE THREAD

**Issue by neeravshahpocketapp** [numandev1/react-native-compressor#157]
### Current behavior
While compressing video after recording a video from a camera it compresses the video size to 140MB while the original size of the video is 373MB 
So to further reduce the size and check the video quality I tried to change the bitrate value but after changing few bitrate value its doesn't reduce the app size to a smaller size. 
I tried the bitrate value as below with compress file size
1. bitrate 100000 - file size 140mb
2. bitrate 1000000 - file size 136mb
3. bitrate  2000000 - file size 136 mb
4. bitrate  4000000 - file size 140 MB 

### Expected behavior
What we want is to compress the video with different bitrates and check the video quality after compression as we want to reduce the video by at least 70% from its original size
### Platform

- [X] Android
- Android version 13 
- [X] iOS

### React Native Version
react-native version 0.66.4
### React Native Compressor Version
react-native-compressor 1.6.1
###      await Video.compress(
            _path,
            {
           compressionMethod: Platform.OS == 'android' ? 'manual' : 'manual',
              minimumFileSizeForCompress:2,
              bitrate:Platform.OS == 'android'? '100000' : '700000'
            },
            (progress) => {
            setProgressStatusValue(progress*100)
            }
          );

**Comment by LemoineThomas** [comment]
Same problem for me. I have a 124mb video and it is scaled down to 107mb. I can't reduce it any more.
Did you find a solution?

**Comment by numandev1** [comment]
🙏 sorry for a long ago I was not maintaining due to the huge office workload, hopefully, I am going to start fixing bugs on a weekend basis,
I will fix at least 2 issues on the weekend, for priority bugs you can join the discord channel https://discord.gg/dtYzk8sp where we can discuss which bug is most important

**Comment by numandev1** [comment]
@Prathamesh-2332 is it taking more time to compress on android or ios?

**Comment by numandev1** [comment]
@Prathamesh-2332 @LemoineThomas @neeravshahpocketapp  can you check the latest version and verify if this issue happens again?

**Comment by numandev1** [comment]
@neeravshahpocketapp bitrate does not work if you are using auto video compression, if you wanna reduce more then you should go with manual compression where bitrate works
