### ISSUE TITLE
Audio Error: Can't stop due to wrong state(INITIALIZED)

### ISSUE THREAD

**Issue by RamKumar-27** [numandev1/react-native-compressor#172]
@numandev1  Here, I am trying to compress audio file. But I am facing this Error.
**My Implementation**
`Audio.compress(
        'file:///data/user/0/com.quranmobile/cache/ac9ec453-f614-4c5c-8cb9-585765613842/file_example_MP3_700KB.mp3',
        {quality: 'high'}
      )
        .then(outputFilePath => {
          console.log('success', outputFilePath);
        })
        .catch(e => {
          console.log(e, 'error');
        });`

### Current behavior
Facing error while compressing audio file
` Error: Can't stop due to wrong state(INITIALIZED)`

### Expected behavior
Need compressed URI

- [x] Android
- Version 10

### React Native Version
0.71.11

### React Native Compressor Version
1.7.0

**Comment by numandev1** [comment]
can you check android audio compression in `1.8.6`

**Comment by sahloulmouhib** [comment]
thank you for replying, but unfortunately, I tried it now with version `1.8.6` and it still does not work on Android

**Comment by numandev1** [comment]
@sahloulmouhib can you paste a file uri here which you are getting from picker

**Comment by sahloulmouhib** [comment]
> @sahloulmouhib can you paste a file uri here which you are getting from picker

 file:////data/user/0/com.asc.anypli.client/cache/sound.mp4

**Comment by numandev1** [comment]
@sahloulmouhib you should pass audio file not video file in it, file extension should be like mp3, wav etc

**Comment by sahloulmouhib** [comment]
> @sahloulmouhib you should pass audio file not video file in it, file extension should be like mp3, wav etc

In android when you record an audio it returns it in mp3 format, I use this library for audio recording react-native-audio-recorder-player

**Comment by numandev1** [comment]
above File uri is showing that you are passing mp4 file, can you try to pass mp3 file and check?

**Comment by sahloulmouhib** [comment]
> above File uri is showing that you are passing mp4 file, can you try to pass mp3 file and check?

I don't have control over that unless I use another library like ffmpeg to do the conversion, In android the type of the recorded audio is mp4 and in ios is m4a I think iOS and Android has license issue with mp3 codec

**Comment by numandev1** [comment]
i am going to enjoy with family, when i will be back i will help you in zoom session

**Comment by sahloulmouhib** [comment]
> i am going to enjoy with family, when i will be back i will help you in zoom session

Okay thank you for your help, just one question are there breaking major changes between version 1.7.2 and version 1.8.6 because we are going to push the app to production and I already used the older version for compressing videos and Images

**Comment by numandev1** [comment]
@sahloulmouhib there is no break changes, you can update, please test the functionality after update

**Comment by numandev1** [comment]
@sahloulmouhib are you available now for zoom session?

**Comment by sahloulmouhib** [comment]
> @sahloulmouhib are you available now for zoom session?

yes

**Comment by numandev1** [comment]
@sahloulmouhib can you connect with me on linkedin https://www.linkedin.com/in/numandev/

**Comment by sahloulmouhib** [comment]
> @sahloulmouhib can you connect with me on linkedin https://www.linkedin.com/in/numandev/

I've sent you an invite

**Comment by numandev1** [comment]
@sahloulmouhib can you try `1.8.7`?

**Comment by sahloulmouhib** [comment]
> @sahloulmouhib can you try `1.8.8`?

It's working fine thank you so much, and I needed to do some modification for android path
`const compressedAudioPath = await AudioCompressor.compress(audioPath);
    const newCompressionPath = isIosDevice()
      ? compressedAudioPath
      : compressedAudioPath.replace('file://', 'file:////');`

**Comment by numandev1** [comment]
@sahloulmouhib why do you need to replace the compressed audio path with `file:////`? can you open another issue? from above comment 

![Screenshot 2023-10-09 at 4 41 45 PM](https://github.com/numandev1/react-native-compressor/assets/36044436/3474a122-12b2-4091-bd5c-46138fb5cc68)
