### ISSUE TITLE
Unhandled Promise Rejection first time Video compress is run

### ISSUE THREAD

**Issue by joshwinter** [numandev1/react-native-compressor#175]
### Current behavior

I'm getting an error message and the compressor is failing the first time I attempt to compress a video with Video.compress. Subsequent compression attempts with no reloading work great. This is happening on a real device in Debug mode.

The error is:
Possible Unhandled Promise Rejection (id: 0):
Error: Exception in HostFunction: <unknown>
Error: Exception in HostFunction: <unknown>  at nativeFlushQueueImmediate (native)

The only two relevant lines I could pull out are:
at compress:
function compress(_x5, _x6, _x7) {

-and-
at ?anon_0_:
var result = yield _$$_REQUIRE(_dependencyMap[7], "react-native-compressor").Video.compress(myUri, {

Also, thanks for a terrific library!

### Expected behavior

I'm able to run Video.compress with no issues the first time it's called.

### Platform

- [ ] Android
- [X] iOS

### React Native Version

0.71.11

### React Native Compressor Version

1.7.2

### Reproducible Steps And Demo

Run the example code with a local video uri such as: file:///var/mobile/Media/DCIM/108APPLE/IMG_8476.MP4 - the video will fail to compress and my debugger shows an error.
When the exact same file is run through Video.compress a second time everything works great.

const result = await Video.compress(
    myUri,
    {
      compressionMethod: 'auto',
    },
    (progress) => {
      console.log('Compression Progress: ', progress);
    }
  );

**Comment by numandev1** [comment]
@joshwinter are you using new arch?

**Comment by joshwinter** [comment]
> @joshwinter are you using new arch?

I just upgraded my RN version to 0.72.0 after reading your message so I could properly turn on new arch (the latest version of reanimated didn't want to work with new arch using 0.71.11) - so I had no choice.

I ran Video.compress without new arch turned on and it worked perfectly the first time.

I think we can close this. Thanks again.
