### ISSUE TITLE
Cannot Compress Audio In Android

### ISSUE THREAD

**Issue by sahloulmouhib** [numandev1/react-native-compressor#177]
### Version of react-native-compressor
1.7.2

### Version of React Native
0.71.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
 const compressedAudio = await Audio.compress(audioPath);
compressedAudio will have the path of the comressed audio
### Current  behavior
 const compressedAudio = await Audio.compress(audioPath);
In Android  when awaiting the path of the compressed audio it does not return anything it is stuck there, but in ios it works perfectly I don't know if it is not implemented in Android

### Steps to reproduce the behavior
In Android record audio with react-native and get the path using  "react-native-audio-recorder-player" version 3.5.4
and them compress the audio using "react-native-compressor" version 1.7.2

**Comment by numandev1** [comment]
can you check android audio compression in `1.8.6`
