### ISSUE TITLE
Build failed on android

### ISSUE THREAD

**Issue by tannguyen05** [numandev1/react-native-compressor#182]
Build fail when add react-native-compressor package in project build failed on android only. On iOS works well.

### Platform

- [X] Android

### React Native Version

"react-native": "0.72.4"

### React Native Compressor Version

"react-native-compressor": "^1.8.2",

### Project build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.7.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}
```
### Build output

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-compressor:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 20s
```

**Comment by techgrih** [comment]
i have same problem

Task :react-native-compressor:compileReleaseKotlin FAILED
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (20, 1): Class 'CompressorModule' is not abstract and does not implement abstract base class member public abstract fun createVideoThumbnail(fileUrl: String?, options: ReadableMap?, promise: Promise): Unit defined in com.reactnativecompressor.CompressorSpec
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (153, 3): 'createVideoThumbnail' overrides nothing
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (158, 3): 'clearCache' overrides nothing

**Comment by techgrih** [comment]
i have same problem 

Task :react-native-compressor:compileReleaseKotlin FAILED
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (20, 1): Class 'CompressorModule' is not abstract and does not implement abstract base class member public abstract fun createVideoThumbnail(fileUrl: String?, options: ReadableMap?, promise: Promise): Unit defined in com.reactnativecompressor.CompressorSpec
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (153, 3): 'createVideoThumbnail' overrides nothing
e: D:\wamp64\www\react-native-projects\onlinelearning\node_modules\react-native-compressor\android\src\main\java\com\reactnativecompressor\CompressorModule.kt: (158, 3): 'clearCache' overrides nothing

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-compressor:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

React Native Version
"react-native": "0.72.4"

React Native Compressor Version
"react-native-compressor": "^1.8.2",

**Comment by numandev1** [comment]
@tannguyen05 @techgrih fixed this error into `1.8.3` version, can you try this version and let me know?

**Comment by tannguyen05** [comment]
> @tannguyen05 @techgrih fixed this error into `1.8.3` version, can you try this version and let me know?

@numandev1 Many thanks; that works. 🎉

**Comment by techgrih** [comment]
> @tannguyen05 @techgrih fixed this error into `1.8.3` version, can you try this version and let me know?

@numandev1 Thank you  ;

**Comment by hamdij0maa** [comment]
happening again in last update

**Comment by numandev1** [comment]
@hamdij0maa which Kotlin version, you are using? can you check `build.gradle` for kotlin version

**Comment by hamdij0maa** [comment]
@numandev1  kotlin_version is 1.7.0 
am getting this error : 
* What went wrong:
Execution failed for task ':react-native-compressor:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by numandev1** [comment]
@hamdij0maa  can you share your `build.gradle` file and react native version?

**Comment by hamdij0maa** [comment]
build.gradle:
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlin_version = '1.7.0'
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

  "react-native": "0.72.5",
  
  PS: the build was working fine before the version : 1.8.4

**Comment by numandev1** [comment]
@hamdij0maa can you try `1.8.8`

**Comment by hamdij0maa** [comment]
done thank you

**Comment by numandev1** [comment]
@hamdij0maa is it working now?

**Comment by hamdij0maa** [comment]
yes fixed 😍 thnx man

**Comment by ngoducduy** [comment]
I'm facing this issue again on version 1.10.3
react-native: 0.76.3
expo: 52.0.0

```
* What went wrong:
Execution failed for task ':react-native-compressor:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
   
My build.gradle:
`buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '35.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '26')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '35')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '34')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.9.24'

        ndkVersion = "26.1.10909125"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath('com.android.tools.build:gradle')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')
    }
}`
