### ISSUE TITLE
Convert to .mp4

### ISSUE THREAD

**Issue by L-U-C-K-Y** [numandev1/react-native-compressor#183]
### Current behavior

Hi all

Thanks for this great library. 
I noticed that it does not always convert all videos to mp4. Is this a desired behavior? I would require them to be in mp4. 

![image](https://github.com/numandev1/react-native-compressor/assets/14868134/cbda2dd4-c88f-416c-8a3b-0be3987a78a5)

### Expected behavior

All videos are in .mp4. 

### Platform

- [X] Android
- [X] iOS

### React Native Version

0.71.3

### React Native Compressor Version

1.6.4

### Reproducible Steps And Demo

Choose a .mov video

**Comment by numandev1** [comment]
@L-U-C-K-Y can you try `1.8.3` version, I tested and confirmed that it is working on both android and ios on latest version

**Comment by stomataln** [comment]
I am trying 1.8.3 and when I compress a .mov, the result is still a .mov. Is this library doing any transcode to .mp4?

**Comment by numandev1** [comment]
?

**Comment by L-U-C-K-Y** [comment]
> ?

Hi @numandev1 
Sorry had no time testing it yet, will try it this weekend, thank you a lot!

**Comment by gerzonc** [comment]
Did it work?

**Comment by numandev1** [comment]
@L-U-C-K-Y  could you try again as it is working on my side

**Comment by numandev1** [comment]
try latest version, closing for now, Please feel free to reopen if this issue happens again
