### ISSUE TITLE
backgroundUpload is crashing while uploading image in expo

### ISSUE THREAD

**Issue by Chiratna** [numandev1/react-native-compressor#186]
### Current behavior
When I am trying to upload image uisng the backgroundUpload function, the app is crashing. I am using expo for my project.
```typescript
const compressedURI = await Image.compress(image.uri, {
          compressionMethod: 'manual',
          maxWidth: 1920,
          quality: isLessThan2MB ? 1 : 0.3,
          returnableOutputType: 'uri',
        });
const uploadImageRes = await backgroundUpload(
            value.fileUploadUrl,
            compressedURI,
            {
              httpMethod: 'PUT',
              headers: {
                'Content-Type': `image/${fileExtension}`,
              },
            }
          );      
``` 
I have checked, `Image.compress()` is working fine and I can confirm that the `backgroundUpload()` is crashing the app

Error Received
<img width="200" height="440" alt="image" src="https://github.com/numandev1/react-native-compressor/assets/63202408/1c6d7660-4c39-4c10-ae7e-f45715181c75">
 

### Platform

- [X] Android
- [] iOS

### React Native Version
`"react-native": "0.71.8"`
`"expo": ""~48.0.15"`

### React Native Compressor Version
`"react-native-compressor": "^1.8.0"`

**Comment by numandev1** [comment]
@Chiratna can you try `1.8.3` version and let me know?

**Comment by Chiratna** [comment]
@numandev1 worked like charm. Thanks for this amazing package
