### ISSUE TITLE
pod install throws an error

### ISSUE THREAD

**Issue by marcin-piela-800** [numandev1/react-native-compressor#187]
### Current behavior

After installing the library `pod install` throws an error

```
Installing NextLevelSessionExporter (0.4.6)
Installing react-native-compressor (1.8.3)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-compressor` depends upon `React-Fabric`, `React-graphics`, `React-utils`, and `React-debug`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

[!] [Codegen] warn: using experimental new codegen integration
```

Adding `use_modular_headers!` globally breaks other libraries.
Adding `use_modular_headers` just to `react-native-compression` doesn't fix the issue.

### Expected behavior

Should install without issues

### Platform

- [] Android
- [X] iOS

### React Native Version

0.72.3

### React Native Compressor Version

1.8.3

**Comment by numandev1** [comment]
can you try to install a pod like this?
```
pod 'NextLevelSessionExporter', :modular_headers => true
```

**Comment by marcin-piela-800** [comment]
Didn't help, I had to patch react-native-compressor by commenting out the line in podpsec:

```
install_modules_dependencies(s)
```

**Comment by numandev1** [comment]
@marcin-piela-800 are you using `RCT_NEW_ARCH_ENABLED`?

**Comment by marcin-piela-800** [comment]
@numandev1 yes, new architecture with hermes enabled

**Comment by numandev1** [comment]
@marcin-piela-800 did you try `bundle exec pod install` command?

**Comment by numandev1** [comment]
closing for now, please feel free to reopen if you face this issue again
