### ISSUE TITLE
failure to compress on android if react-native-reanimated library is installed

### ISSUE THREAD

**Issue by CadenaCristian** [numandev1/react-native-compressor#188]
### Current behavior

When trying to compress a video in android and you have the react-native-reanimated library installed, you get this error:
TypeError: Cannot read property 'adaptViewConfig' of undefined

### Expected behavior
Should compress the video without any problem, since they are different libraries that do not interact.

### Platform
- [X] Android

### React Native Version
0.72.4

### React Native Compressor Version
^1.8.3

### Reproducible Steps And Demo
Install version "react-native-compressor": "^1.8.3" of and "react-native-reanimated": "^3.5.2"

**Comment by numandev1** [comment]
@CadenaCristian it is working on my side, can you provide any repro github example?

**Comment by numandev1** [comment]
@CadenaCristian we are already using reanimated lib with this package in example directory 

https://github.com/numandev1/react-native-compressor/blob/24a573028f38cdc0f7bd3753086388fd29103e9e/example/package.json#L32

**Comment by numandev1** [comment]
I think this issue is not from `react-native-compressor` you should open this issue on the `react-native-reanimated` repo, i am closing it now, please feel free to reopen it if you have this error again
