### ISSUE TITLE
Package not working in expo rect-native v 0.72 expo sdk v 48.0.0 .

### ISSUE THREAD

**Issue by dashingvinit** [numandev1/react-native-compressor#192]
### Current behavior
 ERROR  Error: The package 'react-native-compressor' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Expected behavior
I am using react-native version 0.72 so its much higher than supported version of auto linking.

### Platform
Expo react-native.

### React Native Version
0.72

### React Native Compressor Version
"1.8.4"

### Reproducible Steps And Demo
import {Image} from 'react-native-compressor'

**Comment by numandev1** [comment]
@dashingvinit are you using `npx expo prebuild` command?

**Comment by numandev1** [comment]
can you try 1.8.5

**Comment by mkhoussid** [comment]
> can you try 1.8.5

Same issue here, and version 1.8.5 doesn't work either.

**Comment by numandev1** [comment]
@mkhoussid did you try `npx expo prebuild`
