### ISSUE TITLE
I want to convert mov video to MP4

### ISSUE THREAD

**Issue by jimmy-bull** [numandev1/react-native-compressor#195]
Hello, I wanted to know if it was possible to convert a video to MP4 with this native responsive compressor.
the problem is that when React-Native-Compressor compresses the video, it directly converts it to MP4, but when the video is not larger than minimumFileSizeForCompress, the video is not compressed, so the video is not converted .

**Comment by numandev1** [comment]
@jimmy-bull so what is the problem? I am unable to understand?🙏

**Comment by jimmy-bull** [comment]
by the way, I have a video in mov format that I would like to convert to mp4.

I observed that when React-Native-Compressor compresses videos, it directly converts them to mp4. but when the video is smaller than the FileSizeForCompress minimum, the video is not compressed, so the video file remains in the same format. what I want is that even when the video is not compressed, is it possible to convert the video to MP4.

**Comment by zzz08900** [comment]
I just started trying out the library and by the look of things, setting [minimumFileSizeForCompress](https://github.com/numandev1/react-native-compressor#minimumfilesizeforcompress-number-default-0) to 0 should force the compressor to compress/convert the video to mp4. 

@jimmy-bull maybe you can try that?

**Comment by numandev1** [comment]
@jimmy-bull which version of this package, you are using?

**Comment by numandev1** [comment]
@zzz08900 in new versions, `minimumFileSizeForCompress` having by default 0

**Comment by numandev1** [comment]
@jimmy-bull did you check latest version

**Comment by numandev1** [comment]
already fixed in latest version, please feel free to reopen If you get this issue again
