### ISSUE TITLE
Compile error on Android

### ISSUE THREAD

**Issue by zzz08900** [numandev1/react-native-compressor#198]
### Current behavior
Compile fails with following error message

`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (8, 8): Unresolved reference: io`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (9, 8): Unresolved reference: io`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (47, 27): Unresolved reference: ProgressHelper`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (47, 70): Unresolved reference: ProgressUIListener`
`e: ***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (49, 13): 'onUIProgressStart' overrides nothing`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (50, 23): Unresolved reference: onUIProgressStart`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (54, 13): 'onUIProgressChanged' overrides nothing`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (65, 13): 'onUIProgressFinish' overrides nothing`
`e: /***/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt: (66, 23): Unresolved reference: onUIProgressFinish`

### Expected behavior
Compile and runs

### Platform

- [X] Android
- [ ] iOS

### React Native Version
0.69

### React Native Compressor Version
1.8.7

**Comment by numandev1** [comment]
@zzz08900 let me check

**Comment by zzz08900** [comment]
I also tried older versions including 1.7.x and 1.6.x and seeing the same "Unresolved reference to some kotlin stuff" error.
Am I missing something here?

**Comment by hirbod** [comment]
As already pinged in our repo, I can confirm this. We had to revert back to 1.8.4

**Comment by zzz08900** [comment]
I think I see the problem, thanks for the heads up by @hirbod 
In 1.8.4 `implementation 'io.github.lizhangqu:coreprogress:1.0.2'` is listed under dependencies in build.gradle and in 1.8.7 this dep is gone but some files still kept the reference to that package.

**Comment by numandev1** [comment]
@zzz08900 thanks i am testing, I will release a fixed version in 10 minutes after testing

**Comment by numandev1** [comment]
@zzz08900 can you try `1.8.8` version?

**Comment by zzz08900** [comment]
1.8.8 works alright. But I couldn't play video files generated by any version of `react-native-compressor ` on my android phone nor with VLC with codec errors.
I'm trying to figure out that now.
