### ISSUE TITLE
Image compression using 'auto' affects the quality more than WhatsApp algorithm

### ISSUE THREAD

**Issue by marcopacurariu3** [numandev1/react-native-compressor#200]
Hello, I started usign this library and, according to the documentation, I was expected similar results of this library with the WhatsApp algorithm. However, I noticed a very big difference in quality, without even zooming too much into the picture.

I will provide you two links to see the differences. Out of the same original image, one was compressed by attaching it to WhatsApp, the other by using react-native-compressor.

[library compression](https://drive.google.com/file/d/1W7xj0gx-L2l773At56paMowrQL1hsDcY/view?usp=sharing)
[whatsapp compression](https://drive.google.com/file/d/1uaNjFoCIM7N6ZqlFskDcKWQYDvO0kBNS/view?usp=sharing)

You will see very big differences if you zoom over the screen in the picture, with react-native-compressor you don't see the text very good.

Could you please explain me if there is any setting to improve the quality? In the meanwhile I will play with the 'manual' customization property, but maybe you can provide some info about this quality loss.

Thanks a lot!

**Comment by marcopacurariu3** [comment]
Found the issue: I noticed in the documentation that the default value for maxWidth and maxHeight is 1280, this is what affected my quality so hard.

**Comment by numandev1** [comment]
@marcopacurariu3 if you think, the documentation is not clear, you can make a PR, I will welcome your PR
