### ISSUE TITLE
Cannot find libCompressor.a

### ISSUE THREAD

**Issue by AwolDes** [numandev1/react-native-compressor#204]
### Current behavior
When running a build after manually linking the `libCompressor.a` file, I receive the following error

```
clang: error: no such file or directory: '/Users/austin/Library/Developer/Xcode/DerivedData/PROJECT_NAME/Build/Products/Debug-iphonesimulator/libCompressor.a'
```

In Xcode, the file is displayed in `red`, and the file definitely does not exist on my file system
![CleanShot 2023-10-05 at 14 48 19](https://github.com/numandev1/react-native-compressor/assets/9693812/38364697-d65c-46d1-bfb7-0eeed63a459a)

And this is the path that Xcode is using. I have attempted with and without the Target Membership chcked, and also tried to use the file path `~/Users/...../Build/Products/Debug-iphonesimulator/react-native-compressor/libreact-native-compressor.a` which also did not work
![CleanShot 2023-10-05 at 14 48 47](https://github.com/numandev1/react-native-compressor/assets/9693812/abbab9e0-69d1-43e9-a55d-39fcb1f342f3)

The file has been added to the `Build Phases` step as `required` - the order of the included libraries does not seem to matter
![CleanShot 2023-10-05 at 14 50 39](https://github.com/numandev1/react-native-compressor/assets/9693812/ac72cd94-0c55-4b96-89ac-0b9e725dd1c8)

I attempted adding a bridging file after reading https://github.com/numandev1/react-native-compressor/issues/87 and still no luck. My current theory is requiring a React Native update but hoping to avoid that if possible.

### Expected behavior
A successful build after manually linking

### Platform

- [X] iOS

### React Native Version
0.69.4

### React Native Compressor Version
^1.8.9

### Target iOS Version
12.4

### Xcode Version
14.3.1

### Reproducible Steps And Demo
My project is not set up to use Autolinking, and so I have followed the steps to manually link the file as the documentation describes. I have attempted clean builds, removing the `DerivedData` directory, and a few other fixes based on research. Any pointers in the right direction would be appreciated.

**Comment by StepanSavin** [comment]
@AwolDes 
Hi, when you add Compressor.xcodeproj to your project library, this file move from node_modules/react-compressor to another directory. That's why build fails.
So, you have to copy it file and turn back it to the node_modules/react-native-compressor.
You also may do following after adding it to the Libraries:
```
yarn remove react-native-compressor
yarn add react-native-compressor
```

This works for me

**Comment by AwolDes** [comment]
@StepanSavin thank you! This did fix the build, appreciate the help.

**Comment by AwolDes** [comment]
Sorry to close this off so soon - it looks like this did not fix my problem. `libCompressor.a` is still not found when added to `Link Binary with Libraries` and it is still looking in the `DerivedData` directory. 

The `Compressor.h` file and `Compressor.mm` file are correctly linked to the `node_modules` directory though. Both have the location set to `Relative to Group` - @numandev1 did anything change in how the project is packaged?
![CleanShot 2023-10-25 at 13 34 49](https://github.com/numandev1/react-native-compressor/assets/9693812/7660a939-d006-47e3-a1f8-d3c5ab4178d2)
![CleanShot 2023-10-25 at 13 35 30](https://github.com/numandev1/react-native-compressor/assets/9693812/92f20138-618f-483f-970d-a8d18ea10994)

**Comment by numandev1** [comment]
@AwolDes can we check it on zoom?

**Comment by AwolDes** [comment]
> @AwolDes can we check it on zoom?

It might be easier for me to send a screen recording - I'm based in Australia so timezones might be a bit challenging. Is there any other information I can share to help?

**Comment by tuanduc2904** [comment]
I have same issue

**Comment by numandev1** [comment]
@AwolDes @tuanduc2904 can you try to link this lib like this 
```
pod 'react-native-compressor', :path => '../node_modules/react-native-compressor'
```

**Comment by numandev1** [comment]
> @AwolDes @tuanduc2904 can you try to link this lib like this
> 
> ```
> pod 'react-native-compressor', :path => '../node_modules/react-native-compressor'
> ```
> 
> then `pod install`

please feel free to reopen if above solution does not work
