### ISSUE TITLE
Keep the image background transparency

### ISSUE THREAD

**Issue by Kaosc** [numandev1/react-native-compressor#206]
### Current behavior
Removes the background transparency of the image 

### Expected behavior
It would be cool if we can keep the background transparency

### Platform

- [X] Android
- [ ] iOS

### React Native Version
0.72.5

### React Native Compressor Version
1.8.9

### Reproducible Steps And Demo
![image](https://github.com/numandev1/react-native-compressor/assets/53894007/ecef320b-897a-4dde-92ab-9ee32b7a58a9)

**Comment by numandev1** [comment]
@Kaosc can you paste your code, how you are compressing the image

**Comment by numandev1** [comment]
@Kaosc i will fix it today

**Comment by numandev1** [comment]
@Kaosc fixed and released in `1.8.12`, can you try

**Comment by Kaosc** [comment]
@numandev1 Yep, it has been fixed. Thank you for the fast response.

One more thing that could be considered a feature request: If it's possible, you consider supporting GIFs or other moving picture formats in addition to static images? Currently, the images that are returned lose the ability to move like GIFs. I'm filtering them myself, but it could be a really cool feature, though.
