### ISSUE TITLE
AVFoundationErrorDomain Code=-11847 when compress video in background mode

### ISSUE THREAD

**Issue by tuandat732** [numandev1/react-native-compressor#211]
### Current behavior
- When compress video in ios. I put my app in background. After 60s, put app in foreground. Then repeat many time => App throw error
- Or when compress video in ios. Then put app in background long time => App throw error
```
terminating app due to uncaught exception 'error domain=avfoundationerrordomain code=-11847 "
``` 
![image](https://github.com/numandev1/react-native-compressor/assets/47976884/d690a37f-a9fe-41ab-91e7-19cd6f569fdb)

### Expected behavior
Not throw any error and not crash app
### Platform

- [] Android
- [X] iOS

### React Native Version
0.66.1
### React Native Compressor Version
1.8.6

**Comment by numandev1** [comment]
@tuandat732 I think for this purpose, we have to initiate a background task, I will make RND on it and fix it on the weekend

**Comment by tuandat732** [comment]
@numandev1 thankyou, it helps me a lot.

**Comment by bdkha** [comment]
I got same issue, what status of this issue? @numandev1

**Comment by numandev1** [comment]
@bdkha Sorry i was busy with https://github.com/numandev1/react-native-gifsicle/ package, after that I will take care of it

**Comment by numandev1** [comment]
@bdkha can you test one thing, can you call `activateBackgroundTask` before calling `compress` function and after compression call `deactivateBackgroundTask`

```
import { Video } from 'react-native-compressor';


Video.activateBackgroundTask((data) => {
  console.log("Background Mode Expired", data);
  setBackgroundMode(false);
})
  .then((id: any) => console.log("Background Mode Activated", id))
  .catch((error) => console.log("Failed to activate background task", error));

// here you can call Video.compress function

   Video.deactivateBackgroundTask()
     .then((id: any) => console.log("Background Mode Deactivated", id))
     .catch((error) =>
       console.log("Failed to deactivate background task", error)
     );
```

**Comment by numandev1** [comment]
@tuandat732 did you check above solution?

**Comment by bdkha** [comment]
> @bdkha can you test one thing, can you call `activateBackgroundTask` before calling `compress` function and after compression call `deactivateBackgroundTask`
> 
> ```
> import { Video } from 'react-native-compressor';
> 
> 
> Video.activateBackgroundTask((data) => {
>   console.log("Background Mode Expired", data);
>   setBackgroundMode(false);
> })
>   .then((id: any) => console.log("Background Mode Activated", id))
>   .catch((error) => console.log("Failed to activate background task", error));
> 
> // here you can call Video.compress function
> 
>    Video.deactivateBackgroundTask()
>      .then((id: any) => console.log("Background Mode Deactivated", id))
>      .catch((error) =>
>        console.log("Failed to deactivate background task", error)
>      );
> ```
I tried it, but background mode expired before Video.compress done

**Comment by numandev1** [comment]
@bdkha @tuandat732 did you test above solution?

**Comment by numandev1** [comment]
@tuandat732 @bdkha feel free to reopen if you get this issue again after using `activateBackgroundTask` function

https://github.com/numandev1/react-native-compressor#activatebackgroundtaskonexpired-data-any--void-promiseany

**Comment by Hosam-hsm** [comment]
Is it possible to extend the time limit of the background task? Background mode is being expired when compressing large videos in background.
