### ISSUE TITLE
Cancel BackgroundUpload() 

### ISSUE THREAD

**Issue by hamdij0maa** [numandev1/react-native-compressor#212]
Plz how to cancel the backgroundUpload()
are you planing to add it, or do you have an idea how we can manage to make it happen?

**Comment by numandev1** [comment]
@hamdij0maa currently we dont support cancel the backgroupUpload, i will add support for it

**Comment by hamdij0maa** [comment]
that will be great 🚀

**Comment by GunnarAK** [comment]
Hey @numandev1 any idea on when we can expect the first draft of this feature?

My Kotlin/Swift skills are not quite there yet, and I'm trying to get the project to run, but I'm giving it a shot. Will post my work later here.

**Comment by numandev1** [comment]
@GunnarAK I am going to work on it, thanks for you work ❤

**Comment by numandev1** [comment]
released in `1.8.18`
