### ISSUE TITLE
Exif data removed on compress

### ISSUE THREAD

**Issue by dylanFdvhuset** [numandev1/react-native-compressor#220]
### Current behavior

When I compress my images, exif data are removed from my image.

### Expected behavior

I expect to have the same exif in the output or have an option to prevent the compressor from doing it.

### Platform

- [X] Android
- [x] iOS

### React Native Version

0.72.6

### React Native Compressor Version

1.8.12

### Reproducible Steps And Demo

Take a picture with your phone and upload it through the compressor
Check the exif data on the backend side or frontend

**Comment by numandev1** [comment]
@dylanFdvhuset thanks for reporting, i am going to add this in my task list, hopefully i will fix it after 3 to 4 week

**Comment by numandev1** [comment]
@dylanFdvhuset which exif data, you are trying to get from the backend?
on my side I am getting EXIF data



![Image](https://github.com/numandev1/react-native-compressor/assets/36044436/5e688e11-d137-4656-9911-84659a2d5a70)

**Comment by dylanFdvhuset** [comment]
@numandev1 On our images, we have Date original, the coordinates of the place were the photo was taken, the phone manufacturer missing.

Also on Android, the orientation switch to Horizontal.

**Comment by numandev1** [comment]
@dylanFdvhuset can you try `1.8.15` version as i added exif copy support in this version

**Comment by SirCameron** [comment]
I'm using `1.10.5` and gps location is being stripped from the image meta data after compression.
