### ISSUE TITLE
Crash:  ImageCompressor.swift - Line 106

### ISSUE THREAD

**Issue by truongnguyen3** [numandev1/react-native-compressor#221]
### Current behavior
I got a crash issue when calling `Image.compress` function

stack traces in firebase crashlytics:
![image](https://github.com/numandev1/react-native-compressor/assets/148203070/16eee836-9529-466b-acf5-4cfef01bc848)

### Expected behavior
Not crash at all

### Platform
only happens in iOS
- [ ] Android
- [X] iOS

### React Native Version
0.69.12

### React Native Compressor Version
latest: 1.8.12

### Reproducible Steps And Demo
I will create a new repo later. The crash issue happens in a project at work.

**Comment by numandev1** [comment]
@truongnguyen3 i think, you are giving wrong path of file and code is trying to get the size of that file and crashing

**Comment by truongnguyen3** [comment]
Let me check the file path.
anyway we should catch that crash and throws an error like: "path is wrong", right?

**Comment by numandev1** [comment]
@truongnguyen3 there is already a catch block 

https://github.com/numandev1/react-native-compressor/blob/e59879096698371c9e4a3e2197a485bd90406a87/ios/Image/ImageMain.swift#L23

i don't know why it did not trigged

**Comment by pierroo** [comment]
I am facing the same issue on ios;
I jumped from 1.5.2 to 1.8.3 where the error occurs

my image url is from react-native-view-shot which gives a path like /private/var/mobile/etc

What happened that such path is no longer working with Image.compress @numandev1 ?

**Comment by numandev1** [comment]
@pierroo let me create issue on GitHub task board and will fix it

**Comment by numandev1** [comment]
@pierroo create a task for it on github board, hopefully i will fix it soon https://github.com/numandev1/react-native-compressor/issues/222

**Comment by numandev1** [comment]
fix released in 1.8.14

**Comment by LouisSyfer** [comment]
Hi everybody !

Is it really fixed ? I have exactly the same issue described above and I'm using the last version... 

Thanks in advance for your help
