### ISSUE TITLE
Question: Any way to start uploading while compression is in progress

### ISSUE THREAD

**Issue by murat-mehmet** [numandev1/react-native-compressor#226]
I can see that this library supports both compression and background upload, which is great. 

I am desperately looking for a way to start compression and upload at the same time. In a perfect world, there would be this method: 
```
Video.compressUpload(url, fileUrl, {uploadType: UploadType.MULTIPART, httpMethod: 'POST', headers, compressionMethod: 'auto'})
```
It would start the compression, get a read stream of the new file and start uploading to the server. So the compression + upload process would be twice as fast as it is currently. Is this even possible? I could not find any source or a starting point to get this done cross-platform. Maybe I could hardly get it done in android but I'm a beginner on iOS.

**Comment by numandev1** [comment]
@murat-mehmet Currently, we don't support stream, on android i just do not expose stream but it is in the code if you see native compression code, this is a feature request, if you can make it possible then I welcome you or otherwise I will do this after many of task list in my list
