### ISSUE TITLE
createVideoThumbnail is not returning the thumbnail uri

### ISSUE THREAD

**Issue by AndrePereiraSF** [numandev1/react-native-compressor#230]
### Current behavior

In the [documentation](https://github.com/numandev1/react-native-compressor#createvideothumbnail-fileurl-string-options-headerobject--promise-path-stringsize-number-mime-string-width-number-height-number-) it says that createVideoThumbnail returns the uri of the thumbnail, but it's not returning on my project. And even the object presented there does not have an uri. I don't know if it's exactly a bug or just a lack of attention on my part. I would be grateful if you could help me. 

### Platform

- [X] Android

### React Native Version

0.72.4

### React Native Compressor Version

1.8.15

### Reproducible Steps And Demo

Just try createVideoThumbnail in your environment

**Comment by numandev1** [comment]
@AndrePereiraSF i have assigned this task to me in GitHub task board hopefully look into this today

**Comment by numandev1** [comment]
@AndrePereiraSF I just tested the example directory of this repo and confirmed that it is working as expected on my side, on which device, you are testing

**Comment by numandev1** [comment]
@AndrePereiraSF can you show me the URI of video?

**Comment by AndrePereiraSF** [comment]
@numandev1 Is it returning a uri to you?

I'm using this video uri for testing: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by AndrePereiraSF** [comment]
@numandev1 I'm using a Xiaomi device to test, Android 12, MIUI 14.

The idea is to get the video from the device camera or gallery using another library, then compress and create a thumbnail using yours. For now I'm using the link I sent you to test.

**Comment by numandev1** [comment]
@AndrePereiraSF i just test, i confirm that it is working on my side, can you check it on another device if it is device-specific issue or other issue

**Comment by numandev1** [comment]
@AndrePereiraSF ?

**Comment by AndrePereiraSF** [comment]
Hey @numandev1 sorry for the delay. I found a way to show a thumbnail just using the .mp4 file uri with a Image component, it already solves the problem for me. Also tested the createVideoThumbnail again and it's working, I don't know if I was doing something wrong so sorry for bothering and thank you very much!

**Comment by numandev1** [comment]
@AndrePereiraSF No problem, closing this issue for now, please feel free to reopen if you get this issue again
