### ISSUE TITLE
development build is failing on expo development build

### ISSUE THREAD

**Issue by segun-flexible** [numandev1/react-native-compressor#240]
after installing this package, and i run expo prebuild, and then i run "eas build --profile development" for android, the build failed after some minute, please check the image for the error

![image](https://github.com/numandev1/react-native-compressor/assets/52238200/8c34ef9b-625e-4303-badc-a64f412992eb)

**Comment by numandev1** [comment]
@segun-flexible this issue does not look from this package, are you sure if you remove this package then everything will work fine?

**Comment by segun-flexible** [comment]
Have seen that is not from the package, but this issue started immediately I install your package and run expo prebuild, and then when I run expo development build , that's when I got the error on the build

Please can you look into the error and help detect what's wrong

**Comment by segun-flexible** [comment]
i have been able to fix the issue, 
to anybody from the future who might have this same issue.

if you are on expo, once you install this package, do not run the expo prebuild, just run the expo development build straight.
Enjoy

**Comment by segun-flexible** [comment]
i have been able to fix the issue, 
to anybody from the future who might have this same issue.

if you are on expo, once you install this package, do not run the expo prebuild, just run the expo development build straight.
Enjoy

**Comment by numandev1** [comment]
i think, other package is making your mainApplication.java buggy as i am not doing anything in prebuild
