### ISSUE TITLE
Add a method to return Image metadata like getVideoMetadata()

### ISSUE THREAD

**Issue by ursnj** [numandev1/react-native-compressor#241]
### Current behavior

There is no way to get image metadata from this lib

### Expected behavior

Please add a method to return Image metadata like getVideoMetadata()

### Platform

- [X] Android
- [X] iOS

### React Native Version

0.72

**Comment by numandev1** [comment]
@ursnj released in 1.8.20, can you try `getImageMetaData` now?

**Comment by ursnj** [comment]
Thanks @numandev1 , Its real Quick :)

**Comment by VimukthiShohan** [comment]
@ursnj is there a method to get the timestamp of the video and image? Like created at.

**Comment by VimukthiShohan** [comment]
@numandev1 is there a method to get the timestamp of the video and image? Like created at.
