### ISSUE TITLE
unable to compress files in parallel

### ISSUE THREAD

**Issue by segun-flexible** [numandev1/react-native-compressor#246]
am working on a social media app where they can make a post with media, and once they click on submit button, it take then to homepage, while the compressing is still going on, if they try to make another post again with media, it will show this error

"ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or heigh. Conversion failed"

This error happen if compressing or background upload is going on in the background, user cant make another post with media again.

**Comment by numandev1** [comment]
@segun-flexible cab you paste your code, i wanna get reproducible example so i can fix this type of usecase, Note, we are not using ffmpeg

**Comment by segun-flexible** [comment]
//Upload Post With Media
            for (i = 0; i < Object.values(selectedMedias).length; i++) {

              let sm = Object.values(selectedMedias)[i];

              //GETTING CORRECT FILE PATH ON IOS
              if (Platform.OS == "ios") {
                const realPath = await getRealPath(sm.uri, sm.mediaType);
                console.log('realpath', realPath);
                const asset = await MediaLibrary.getAssetInfoAsync(sm.uri.split('ph://')[1]);
                sm = { ...sm, uri: asset.localUri }
              }

              if (sm.mediaType == "photo") {

                const result = await ImageCompressor.compress(sm.uri, {
                  compressionMethod: 'manual',
                  maxWidth: sm.width,
                  quality: 0.3,
                });
                sm = { ...sm, uri: result }

              } else if (sm.mediaType == "video") {

                const result = await VideoCompressor.compress(sm.uri, {
                  compressionMethod: "manual",
                  bitrate: 1200000
                });
                sm = { ...sm, uri: result }

              }

              files.push({
                uri: sm.uri,
                name: `${sm.filename}`,
                type: sm.mediaType == "photo" ? "image/png" : mime.getType(sm.uri)
              })
            }

**Comment by numandev1** [comment]
@segun-flexible i just checked and confirm that no issue with parallel image compression, I think `MediaLibrary` is crashing

**Comment by segun-flexible** [comment]
Thanks 🙏
