### ISSUE TITLE
Apparently linked problem using Jest

### ISSUE THREAD

**Issue by ManuF17** [numandev1/react-native-compressor#250]
### Current behavior

The package is working fine, but when i trying to run couple of tests they are failing because of the following error:

<img width="990" alt="Screenshot 2023-11-20 at 8 28 51 a m" src="https://github.com/numandev1/react-native-compressor/assets/147534645/494c797d-949e-4d82-8e90-68f39f6e0b0c">

### Expected behavior

During our tests won't see any error related to this package.

### Platform

- [X] Android
- [X] iOS

### React Native Version

0.72.6

### React Native Compressor Version

1.8.12

**Comment by murat-mehmet** [comment]
You should mock it:
```
jest.mock('react-native-compressor', () => ({
    Image: {
        compress: uri => uri
    }
}));
```
