### ISSUE TITLE
Question: How to upload with Multipart?

### ISSUE THREAD

**Issue by kusche12** [numandev1/react-native-compressor#265]
### Current behavior
The documentation mentions that we can use backgroundUpload() with upload type MULTIPART. I've never seen a Multipart upload solution that works with a single endpoint URL, so I am curious to learn more.

Can someone explain to me what I need to do to get a single S3 URL that I can use in this function? My app currently uses a Presigned S3 URL for a single video upload, but this URL does not work when uploadType is set to Multipart.

### Expected behavior
I pass a single S3 Presigned URL, my file path, and uploadType === Multipart, and react-native-compressor will handle the multi-part upload in the background.

### Platform

- [X] Android
- [X] iOS

### React Native Version
0.73.2

### React Native Compressor Version
1.82.23

**Comment by numandev1** [comment]
@kusche12 sorry for the late reply, this is how you can use multipart request 

https://github.com/numandev1/react-native-compressor/blob/63a527dcb35b3b83692c685a3d17c34cd51b6d33/example/src/Screens/Video/index.tsx#L216

**Comment by kusche12** [comment]
@numandev1 that looks good to me. I think I just need to change the policies in my S3 bucket to allow Multipart permissions, closing for now!
