### ISSUE TITLE
On image compression android error Width and height must be > 0

### ISSUE THREAD

**Issue by sreedevi111** [numandev1/react-native-compressor#282]
### Current behavior
On compressing image with local path (eg: /Users/Desktop/checkImage.png), getting error on android like 
Width and height must be > 0. In ios it is working fine

### Expected behavior
Image need to be compressed.
### Platform

- [X] Android 

### React Native Version
0.73.6

### React Native Compressor Version
^1.8.24

### Reproducible Steps And Demo
useEffect(() => {
const fetchData = async() => {
try{
const result = await Image.compress('Users/Downloads/image.jpg', {
returnableOutputType: uri
})
console.log("Result", result)
}
catch (e){
console.log("Error", e)
}
fetchData()
},[])

**Comment by Josh2941** [comment]
I am still facing this same issue in the latest version of this package 1.11.0. Any resolutions?
