### ISSUE TITLE
IOS build crash

### ISSUE THREAD

**Issue by serolgames** [numandev1/react-native-compressor#322]
Hello, today I wanted to build my app. I'm using eas with expo, I get the following error : 

❌  (node_modules/react-native-compressor/ios/Video/NextLevelSessionExporter.swift:376:69)

  374 |         for audioTrack in audioTracks {
  375 |             let mediaSubtypes = audioTrack.formatDescriptions.filter { CMFormatDescriptionGetMediaType($0 as! CMFormatDescription) == kCMMediaType_Audio }.map { CMFormatDescriptionGetMediaSubType($0 as! CMFormatDescription) }
> 376 |             for mediaSubtype in mediaSubtypes where mediaSubtype != kAudioFormatAPAC {
      |                                                                     ^ cannot find 'kAudioFormatAPAC' in scope
  377 |                 audioTracksToUse.append(audioTrack)
  378 |             }
  379 |         }

It's quite an urgent issue to solve

### Platform

- [X] iOS

### React Native Version
0.74.5

### React Native Compressor Version
0.10.1

**Comment by gaearon** [comment]
I suppose maybe it'll get fixed by upgrading Xcode to 16?

**Comment by gibbz-one** [comment]
Same error here with Expo 51 and Xcode 15.4

**Comment by numandev1** [comment]
can you check [1.10.2](https://github.com/numandev1/react-native-compressor/releases/tag/v1.10.2) version?
